apiVersion: networking.k8.io/v1beta1
kind: Ingress
metadata:
  name: dockubdeploy-ingress
spec:
  rules:
  - http:
      paths:
      - path: /health
        backend:
          serviceName: dockubdeploy-service
          servicePort: 8000
      - path: /parity
        backend:
          serviceName: dockubdeploy-service
          servicePort: 8000
      - path: /wait
        backend:
          serviceName: dockubdeploy-service
          servicePort: 8000
      - path: /fail
        backend:
          serviceName: dockubdeploy-service
          servicePort: 8000
      - path: /quit
        backend:
          serviceName: dockubdeploy-service
          servicePort: 8000
